using System.Text.Json;
using System.Text.Json.Nodes;

namespace Toolbelt.Blazor.WebAssembly.ExtensibleDevServer.ImportMapExtension;

/// <summary>
/// Edits the JSON of an import map.
/// </summary>
internal static class ImportMapJson
{
    /// <summary>
    /// LF, not the newline of whatever machine is running. The digest a browser computes is over
    /// the text after the HTML parser has turned every newline into LF, so writing LF here makes
    /// the bytes that go out and the bytes that get hashed the same thing.
    /// </summary>
    private static readonly JsonSerializerOptions _WriteOptions = new() { WriteIndented = true, NewLine = "\n" };

    /// <summary>
    /// Returns the import map without its "integrity" member, or <c>null</c> when there was nothing
    /// to remove or the content is not an import map this can understand.
    /// <para>
    /// The member is removed rather than recomputed because the development server answers a
    /// fingerprinted URL with whatever is on disk right now, while the import map is only
    /// regenerated by a build. Any value written here would go stale the moment a module is edited.
    /// </para>
    /// </summary>
    public static string? RemoveIntegrity(string importMapBody)
    {
        JsonNode? root;
        try { root = JsonNode.Parse(importMapBody); }
        catch (JsonException) { return null; }

        if (root is not JsonObject map) return null;
        if (!map.Remove("integrity")) return null;

        // The digest of this text is computed afterwards, so the formatting is free to change.
        return map.ToJsonString(_WriteOptions);
    }
}
